version: '3.8'

services:
  frontend-client:
    image: roblox-case-frontend-client:latest
    build:
      context: ./frontend-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api/v1
    depends_on:
      - backend

  frontend-admin:
    image: roblox-case-frontend-admin:latest
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api/v1
    depends_on:
      - backend

  backend:
    image: roblox-case-backend:latest
    build:
      context: ./backend  # Path to your Spring app
      dockerfile: Dockerfile  # Dockerfile for your Spring app
    ports:
      - "8080:8080"  # Expose Spring app on port 8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/robloxcase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: robloxcase
    ports:
      - "5433:5432"