HOST: localhost
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: roblox-case

spring:
  application:
    name: roblox-case
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    contexts: ${liquibase.contexts}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: db/changelog/master.yaml

  data:
    redis:
      host: ${HOST}
      port: 6379
jwt:
  signing-key: aW5zdGFodWIoY2h1cGFjaHVwczg0LGs0cjNsMW5zLHN3dHk0NSxpcmluYWZlZG9yb3ZpY2gxOTk1KQ==
  expiration:
    access-token: 300000 # 5 min
    refresh-token: 604800000 # 1 week

bot:
  name: pet_case_bot
  token: 7211035777:AAGjtfxt3xE_8l2ZuT18lO9sr0b9c2yGhSU
  chatId: -4267936948